require("dt.base")
require("dt.plugins")
require('p.lualine')
require('p.nvim-treesitter')
require('p.catppuccin')
require('p.telescope')
require('p.null-ls')
require('p.prettier')
require('p.nvim-tree')
require('p.lsp')
require('p.comment')
require("p.rust-tool")
require("p.bufferline")
require("p.gomove")
require("dt.maps")

